- name: start icinga2 container
  docker:
    name: icinga2
    hostname: "{{ ansible_hostname }}-icinga2"
    image: gitinsky/icinga2:0.0.1
    state: started
    links:
    - "mysql:mysql"
    ports:
    - "80:80"
    restart_policy: always
    dns:
    - "{{ docker_dns_2 }}"
    - "{{ ansible_docker0.ipv4.address }}"
