- name: create {{ icinga2.docker_vol_container_env }}
  file: dest={{ icinga2.docker_vol_container_env }} state=directory

- name: set proper permissions on {{ icinga2.docker_vol_tmp }}
  file: dest={{ icinga2.docker_vol_tmp }} state=directory mode=1777

- name: put container_environment.sh
  copy: src=container_environment.sh dest={{ icinga2.docker_vol_container_env }}/container_environment.sh

- name: put container_environment.json
  copy: src=container_environment.json dest={{ icinga2.docker_vol_container_env }}/container_environment.json

#- name: start icinga2 container
#  docker:
#    name: icinga2
#    hostname: "{{ ansible_hostname }}-icinga2"
#    image: gitinsky/icinga2:0.0.1
#    state: started
#    ports:
#    - "{{ icinga2.ext_http_port }}:80"
#    restart_policy: always
#    volumes:
#    - "{{ icinga2.docker_vol_config | mandatory }}:/etc/icinga2/conf.d/custom"
#    - "{{ icinga2.docker_vol_eye_logs }}:/var/log/eye"
#    - "{{ icinga2.docker_vol_container_env }}:/etc/container_environment"
#    - "{{ icinga2.docker_vol_container_env }}/container_environment.sh:/etc/container_environment.sh"
#    - "{{ icinga2.docker_vol_container_env }}/container_environment.json:/etc/container_environment.json"
#    - "{{ icinga2.docker_vol_var_run_eye }}:/var/run/eye"
#    - "{{ icinga2.docker_vol_var_run_apache2 }}:/var/run/apache2"
#    - "{{ icinga2.docker_vol_var_log_apache2 }}:/var/log/apache2"
#    - "{{ icinga2.docker_vol_var_lock_apache2 }}:/var/lock/apache2"
#    - "{{ icinga2.docker_vol_cache }}:/var/cache/icinga2"
#    - "{{ icinga2.docker_vol_log }}:/var/log/icinga2"
#    - "{{ icinga2.docker_vol_var_run_icinga2 }}:/var/run/icinga2"
#    - "{{ icinga2.docker_vol_var_lib_icinga2 }}:/var/lib/icinga2"
#    - "{{ icinga2.docker_vol_tmp }}:/tmp"
#    dns:
#    - "{{ docker_dns_2 }}"
#    - "{{ ansible_docker0.ipv4.address }}"

- name: start icinga2 container
  command: docker run
             -d
             -h {{ ansible_hostname }}-icinga2
             --dns={{ docker_dns_2 }}
             --dns={{ ansible_docker0.ipv4.address }}
             -p={{ icinga2.ext_http_port }}:80
             -v {{ icinga2.docker_vol_config | mandatory }}:/etc/icinga2/conf.d/custom
             -v {{ icinga2.docker_vol_eye_logs }}:/var/log/eye
             -v {{ icinga2.docker_vol_container_env }}:/etc/container_environment
             -v {{ icinga2.docker_vol_container_env }}/container_environment.sh:/etc/container_environment.sh
             -v {{ icinga2.docker_vol_container_env }}/container_environment.json:/etc/container_environment.json
             -v {{ icinga2.docker_vol_var_run_eye }}:/var/run/eye
             -v {{ icinga2.docker_vol_var_run_apache2 }}:/var/run/apache2
             -v {{ icinga2.docker_vol_var_log_apache2 }}:/var/log/apache2
             -v {{ icinga2.docker_vol_var_lock_apache2 }}:/var/lock/apache2
             -v {{ icinga2.docker_vol_cache }}:/var/cache/icinga2
             -v {{ icinga2.docker_vol_log }}:/var/log/icinga2
             -v {{ icinga2.docker_vol_var_run_icinga2 }}:/var/run/icinga2
             -v {{ icinga2.docker_vol_var_lib_icinga2 }}:/var/lib/icinga2
             -v {{ icinga2.docker_vol_tmp }}:/tmp
             --read-only
             --name=icinga2 gitinsky/icinga2:0.0.1

- name: copy configs
  copy: src={{ item.src }} dest={{ icinga2.config_dir | mandatory }}/{{ item.dest }}
  with_items: icinga2.configs
  tags: configure
  notify: restart icinga2
