- name: start icinga2 container
  docker:
    name: icinga2
    hostname: "{{ ansible_hostname }}-icinga2"
    image: gitinsky/icinga2:0.0.1
    state: started
    ports:
    - "{{ icinga2.ext_http_port }}:80"
    restart_policy: always
    volumes:
    - "{{ icinga2.config_dir | mandatory }}:/etc/icinga2/conf.d/custom"
    dns:
    - "{{ docker_dns_2 }}"
    - "{{ ansible_docker0.ipv4.address }}"

- name: copy configs
  copy: src={{ item.src }} dest={{ icinga2.config_dir | mandatory }}/{{ item.dest }}
  with_items: icinga2.configs
  tags: configure
  notify: restart icinga2
